@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzOTczMmE5MTVkOTgzYzg4NGVlMmZiIn0sImlhdCI6MTU2NDA3NDE3OSwiZXhwIjoxNTY0MDg0OTc5fQ.WKjLdBs8yYXYOyy7yXMhvVBR0GlarRldICkqKdqgNJw
@user_id = 5d368e115237283e14932f5a

### Get current user
GET http://localhost:5000/api/auth HTTP/1.1
content-type: application/json
x-auth-token: {{token}}

### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "Alanna_Mitchell@gmail.com",
    "password": "123456"
}

### Register
POST http://localhost:5000/api/user/register HTTP/1.1
content-type: application/json

{
    "name": "Alanna Mitchell",
    "email": "Alanna_Mitchell@gmail.com",
    "password": "123456"
}

### Get current user profile
GET http://localhost:5000/api/profile/me HTTP/1.1
x-auth-token: {{token}}

### Create and update profile
POST http://localhost:5000/api/profile HTTP/1.1
content-type: application/json
x-auth-token: {{token}}

{
    "company": "Hegmann, Smith and Heaney",
    "website": "xavier.info",
    "status": "Developer",
    "skills": "Java, C#",
    "location": "Araceliborough",
    "bio": "I am a developer",
    "githubusername": "alannamitchell",
    "facebook": "https://www.facebook.com/alannamitchell"
}

### Get all profiles
GET http://localhost:5000/api/profile HTTP/1.1

### Get profile by user id
GET http://localhost:5000/api/profile/user/{{user_id}} HTTP/1.1

### Delete user, profile and post
DELETE http://localhost:5000/api/profile HTTP/1.1
x-auth-token: {{token}}

### Add experience to profile
PUT http://localhost:5000/api/profile/experience HTTP/1.1
content-type: application/json
x-auth-token: {{token}}

{
    "title": "Developer",
    "company": "Degv Soft",
    "location": "Udonthani TH",
    "from": "08-10-2010",
    "current": true,
    "description": "Web development"
}

### Delete experience by id
DELETE http://localhost:5000/api/profile/experience/5d3834157cbb635764918fe8 HTTP/1.1
x-auth-token: {{token}}

### Add education to profile
PUT http://localhost:5000/api/profile/education HTTP/1.1
content-type: application/json
x-auth-token: {{token}}

{
    "school": "Khon Kean University",
    "degree": "bachelor",
    "fieldofstudy": "Computer Science",
    "from": "08-02-2003",
    "to": "08-02-2005",
    "description": "Web development"
}

### Delete education by id
DELETE http://localhost:5000/api/profile/education/5d385b81c73046343c37cc5e HTTP/1.1
x-auth-token: {{token}}

### Github
GET http://localhost:5000/api/profile/github/avetavos

### Create new post
POST http://localhost:5000/api/posts
content-type: application/json
x-auth-token: {{token}}

{
    "text": "Sed tenetur quia distinctio cum sint animi est qui non. Quos fugit aut modi impedit maiores veritatis quaerat. Ullam magnam autem et voluptates qui. Sit maiores veniam voluptas nihil."
}

### Get all posts
GET http://localhost:5000/api/posts
x-auth-token: {{token}}

### Get post by id
GET http://localhost:5000/api/posts/5d39734d915d983c884ee2fc
x-auth-token: {{token}}

### Delete post by id
DELETE  http://localhost:5000/api/posts/5d39afeee42b390454a468
x-auth-token: {{token}}

### Like post
PUT  http://localhost:5000/api/posts/like/5d39734d915d983c884ee2fc
x-auth-token: {{token}}

### Unlike post
PUT  http://localhost:5000/api/posts/unlike/5d39734d915d983c884ee2fc
x-auth-token: {{token}}