@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQzOTczMmE5MTVkOTgzYzg4NGVlMmZiIn0sImlhdCI6MTU2NDE0MjgyMCwiZXhwIjoxNTY0MTUzNjIwfQ.UFfcwp2sHUMTeV3eIP2g5i6pYujgCv6HbD7Qg67ZCRw
@user_id = 5d368e115237283e14932f5a

### Get current user
GET http://localhost:5000/api/auth HTTP/1.1
content-type: application/json
x-auth-token: {{token}}

### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "Alanna_Mitchell@gmail.com",
    "password": "123456"
}

### Register
POST http://localhost:5000/api/user/register HTTP/1.1
content-type: application/json

{
    "name": "Alanna Mitchell",
    "email": "Alanna_Mitchell@gmail.com",
    "password": "123456"
}