@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNWQ1OTYzYjc1MDNlOTY0NmNjNWViNjQ5IiwiaWF0IjoxNTY3NTEwMjUwLCJleHAiOjE1Njc1MjEwNTB9.Xnva6DCL8wQsYCO40AFXg5TOnVXvB5vMFkltSCiAmMc
@user_id = 5d368e115237283e14932f5a

### Get current user
GET http://localhost:5000/api/auth HTTP/1.1
content-type: application/json
x-auth-token: {{token}}

### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "avetavos@gmail.com",
    "password": "123456"
}

### Register
POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
    "name": "Alanna Mitchell",
    "email": "Alanna_Mitchell@gmail.com",
    "password": "123456"
}