@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNWQ4NDk5MmE2NGZhNWYzYTE0YTRjNGU0IiwiaWF0IjoxNTY4OTg4NjU5LCJleHAiOjE1Njg5OTk0NTl9.Hom-_hjRNEPLLrsfHzJFUXuCHUHH5vkPOrzUKKwxTkA
@user_id = 5d368e115237283e14932f5a

### Create new post
POST http://localhost:5000/api/posts
content-type: application/json
x-auth-token: {{token}}

{
    "text": "Sed tenetur quia distinctio cum sint animi est qui non. Quos fugit aut modi impedit maiores veritatis quaerat. Ullam magnam autem et voluptates qui. Sit maiores veniam voluptas nihil."
}

### Get all posts
GET http://localhost:5000/api/posts
x-auth-token: {{token}}

### Get post by id
GET http://localhost:5000/api/posts/5d39734d915d983c884ee2fc
x-auth-token: {{token}}

### Delete post by id
DELETE http://localhost:5000/api/posts/5d39afeee42b390454a468
x-auth-token: {{token}}

### Like post
PUT http://localhost:5000/api/posts/like/5d84da28ceb6a817149b259e
x-auth-token: {{token}}

### Unlike post
PUT http://localhost:5000/api/posts/unlike/5d84da28ceb6a817149b259e
x-auth-token: {{token}}

### Add comment to post
POST http://localhost:5000/api/posts/comment/5d39734d915d983c884ee2fc
content-type: application/json
x-auth-token: {{token}}

{
    "text": "Repellat a voluptas voluptatibus sunt quas. Distinctio et delectus adipisci. Omnis quasi itaque sed."
}

### Add comment to post
DELETE http://localhost:5000/api/posts/comment/5d39734d915d983c884ee2fc/5d3aed59e68fa4105cece2f5
x-auth-token: {{token}}